---
title: "Algorithm testing on real data"
author: "Andrea"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
  html_document: 
    dev: pdf
    fig_caption: yes
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
documentclass: article
urlcolor: blue
classoption: a4paper
header-includes:
- \usepackage{graphicx}
- \usepackage{float}
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../reports/bio_data")})
---

```{r setup}
# Functions, Constants and graphical variables      
knitr::opts_knit$set(root.dir = "/data3/arubio/projects/Andrea_CircaN_rebuttal/")
knitr::opts_chunk$set(
	fig.align = "center",
	fig.path = "../reports/bio_data/figures/",
	fig.pos = "H",
	message = FALSE,
	warning = FALSE,
	dev = c("png"),
	dpi = 500,
	root.dir = "/data3/arubio/projects/Andrea_CircaN_rebuttal/"
)
```


<style>
.column-left{
  float: left;
  width: 50%;
  text-align: left;
}
.column-right{
  float: right;
  width: 50%;
  text-align: left;
}
</style>


```{r libraries, fig.show='hide'}
# devtools::install_github("AndreaRP/ArpyLib")
library("ArpyLib")
library("ggplot2")
library("ggforce")
library("cowplot")
library("pheatmap")
library("edgeR")
library("dplyr")
```



```{r graphical_parameters}
colors <- c("#1B9E77", "#D95F02", "#7570B3")
names(colors) <- c("CircaN", "meta2d", "circan_old")
blank_background <- theme(panel.grid.major = element_blank()
                        , panel.grid.minor = element_blank()
                        , panel.background = element_blank())
hmcol <- RColorBrewer::brewer.pal(11,"RdBu")
hmcol <- rev(hmcol) # Invert Red and Blue
```


# Dot plot

```{r}
expr <- as.data.frame(t(as.matrix(GetAssayData(object = neutrophils_subset))[selected_genes,]))
expr$cluster <- neutrophils_subset@meta.data$unbiased_clustering
expr$tissue <- neutrophils_subset@meta.data$tissue
melt_expr <- reshape2::melt(expr, id.vars=c("cluster", "tissue")
                          , value.name="expression", variable.name=c("gene"))
# Get mean expression by cluster
dot_plot_data <- setNames(aggregate(melt_expr[,"expression"], list(melt_expr$cluster, melt_expr$gene), mean)
                        , c("cluster", "gene", "mean"))
# Get %of cells per cluster that express the gene
p <- aggregate(melt_expr[,"expression"], list(melt_expr$cluster, melt_expr$gene), function(x) sum(x != 0)/length(x))
dot_plot_data$pct_expression <- p$x
```


```{r}
ggplot(dot_plot_data, aes(x=gene, y=cluster, size = mean, color=cluster, alpha=pct_expression)) +
    # geom_point(alpha=0.7) +
    geom_point() +
    scale_size(range = c(.1, 15), name="Cluster mean") +
    theme(axis.text.x=element_text(size=10, angle=90, hjust=0.95, vjust=0.2)) +
    blank_background +
    scale_alpha(name = "% Expression") +
    scale_colour_discrete(guide=FALSE)
```


```{r}
ggplot(dot_plot_data, aes(x=gene, y=cluster, size = pct_expression, color=mean)) +
    # geom_point(alpha=0.7) +
    geom_point() +
    scale_size(range = c(.1, 7)
             , name="Pct exp"
             # , breaks=c(0, 1, 2)
             ) +
    scale_color_gradientn(colours = gradient.colors
                        , guide = guide_colourbar(barheight=3, barwidth = 0.5)
                        , name="Mean") +
    theme(axis.text.x=element_text(size=10, angle=90, hjust=0.95, vjust=0.2)
        , axis.title.x=element_blank()
          ) +
    blank_background 
```


# Violin plot

```{r }
score.min <- min(tsnedummy[,chemokines])
score.max <- max(tsnedummy[,chemokines])

score.breaks <- c(score.min, score.max)
score.labels <- c(round(score.min,7), round(score.max,7))

quant_color_scale <- scale_color_gradientn(colours = gradient.colors
                    , guide = guide_colourbar(barheight=0.5, label.vjust=-1)
                    , limits=c(score.min, score.max)
                    )
cols <- ArpyLib::gg.cols(length(unique(tsnedummy$cluster)))
```

## One gene in different clusters

```{r}
vln_temp <- ggplot(tsnedummy, aes(x=cluster, y=tsnedummy[,gene], fill = cluster, color=cluster)) +
              geom_violin() +
              geom_jitter(shape=16, position=position_jitter(width=0.2, height=0)) +
              stat_summary(fun.y=mean, geom="point", size=2, color="black") +
              scale_fill_manual(values=cols) +
              scale_color_manual(values=cols) +
              theme(axis.text.x=element_text(size=10, angle=90,hjust=0.95,vjust=0.2)) +
              ylab("log(10K) TPM") +
              ylim(0, score.max) +
              ggtitle(gene) +
              blank_background +
              theme(axis.text=element_text(size=8)
                  , axis.title=element_text(size=8)
                  , legend.text=element_text(size=7)
                  , legend.position="none"
                  , legend.title = element_blank()
                  , axis.line=element_line(color="grey90")
                  , panel.border = element_blank())
```

## One cluster, different genes

```{r}
temp <- tsnedummy[which(tsnedummy$cluster==c),]
z <- reshape2::melt(temp, measure.vars = chemokines, id.vars = c("tSNE_1", "tSNE_2"))
vln_temp_c <- ggplot(z, aes(x=variable, y=value, fill = variable, color=variable)) +
              geom_violin() +
              geom_jitter(shape=16, position=position_jitter(width=0.2, height=0)) +
              stat_summary(fun.y=mean, geom="point", size=2, color="black") +
              # scale_fill_manual(values=cols) +
              # scale_color_manual(values=cols) +
              theme(axis.text.x=element_text(size=10, angle=90,hjust=0.95,vjust=0.2)) +
              ylab("log(10K) TPM") +
              xlab("Gene") +
              ylim(0, score.max) +
              ggtitle(c) +
              blank_background +
              theme(axis.text=element_text(size=8)
                  , axis.title=element_text(size=8)
                  , legend.text=element_text(size=7)
                  , legend.position="none"
                  , legend.title = element_blank()
                  , axis.line=element_line(color="grey90")
                  , panel.border = element_blank())
```

## Several genes faceted by cluster

```{r}
tsnedummy_hscs <- tsnedummy[tsnedummy$hscs_14_score>0,]
z <- reshape2::melt(tsnedummy_hscs, measure.vars = other_gene_list, id.vars = c("cell", "tissue"))
score_max <- max(tsnedummy_hscs[, other_gene_list])

cols <- ArpyLib::gg_cols(length(unique(tsnedummy$tissue)))
vln_temp <- ggplot(z, aes(x=tissue, y=value
                  , fill = tissue, color=tissue)) +
              geom_violin() +
              geom_jitter(shape=16, position=position_jitter(width=0.2, height=0)) +
              stat_summary(fun.y=mean, geom="point", size=2, color="black") +
              scale_fill_manual(values=cols) +
              scale_color_manual(values=cols) +
              theme(axis.text.x=element_text(size=10, angle=90,hjust=0.95,vjust=0.2)) +
              ylab("log(10K) TPM") +
              ylim(0, score_max) +
              # ggtitle(gene) +
              blank_background +
              theme(axis.text=element_text(size=8)
                  , axis.title=element_text(size=8)
                  , legend.text=element_text(size=7)
                  , legend.position="none"
                  , legend.title = element_blank()
                  , axis.line=element_line(color="grey90")
                  , panel.border = element_blank()) +
  facet_grid(. ~ variable)
```

```{r}
# version mas cuqui
tsnedummy_hscs <- tsnedummy[tsnedummy$hscs_14_score>0,]
z <- reshape2::melt(tsnedummy_hscs, measure.vars = other_gene_list, id.vars = c("cell", "tissue"))
score_max <- max(tsnedummy_hscs[, other_gene_list])
z$tissue <- factor(z$tissue, levels = c("BM", "Blood"))

cols <- ArpyLib::gg_cols(length(unique(tsnedummy$tissue)))
vln_temp <- ggplot(z, aes(x=tissue, y=value
                  , fill = tissue, color=tissue)) +
              geom_violin() +
              geom_jitter(shape=16, position=position_jitter(width=0.2, height=0)) +
              stat_summary(fun.y=mean, geom="point", size=2, color="black") +
              scale_fill_manual(values=cols) +
              scale_color_manual(values=cols) +
              theme(axis.text.x=element_text(size=10, angle=90,hjust=0.95,vjust=0.2)) +
              ylab("log(10K) TPM") +
              xlab("") +
              ylim(0, score_max) +
              # ggtitle(gene) +
              blank_background +
              theme(axis.text=element_text(size=8)
                  , axis.title=element_text(size=8)
                  , legend.text=element_text(size=7)
                  , axis.text.x = element_blank()
                  , axis.line.x = element_blank()
                  , axis.ticks.x = element_blank()
                  , legend.position="bottom"
                  , legend.title = element_blank()
                  , axis.line=element_line(color="grey90")
                  , panel.border = element_blank()) +
  facet_grid(. ~ variable
           , switch="both"
           ) +
  # facet_wrap(. ~ variable, strip.position="bottom") +
  theme(strip.text.x = element_text(size=12, angle=90, face="bold", hjust = 1),
        # strip.text.y = element_text(size=12, face="bold"),
        strip.background = element_rect(colour=NA, fill=NA)) +
  + guides(colour = guide_legend(override.aes = list(shape = NA))) # Quita el punto de la leyenda
```


# UpSet plot

```{r}
algorithms <- list(CircaN=as.character(circan_results[which(circan_results$BH_combined<0.05 & circan_results$r>=0.7), "feature"])
                  , LS=as.character(ls_results[which(ls_results$LS_BH.Q<0.05), "CycID"])
                  , MetaCycle=as.character(metacycle_results[which(metacycle_results$meta2d_BH.Q<0.05), "CycID"])
                  , JTK=as.character(results_jtk[which(results_jtk$BH.Q<0.05), "Probeset"])
                )

library("UpSetR")
upset(fromList(algorithms)
    , order.by = c("degree")
    , queries = list(list(query = intersects , params = list("CircaN"), color = "orchid3", active = T)
                   # , list(query = intersects, params = list("LS"), color = "firebrick3", active = T)
                   , list(query = intersects, params = list("MetaCycle"), color = "seagreen3", active = T)
                   , list(query = intersects, params = list("JTK"), color = "dodgerblue", active = T)
                   )
      , keep.order = T
      , nintersects = NA
      )
```


# Venn Diagram

```{r}
algorithms_i <- venn::venn(x=algorithms
                 , ilab=TRUE
                 , zcolor = "style"
                 , intersections=T
                 , show.plot=F)
intersections <- attr(algorithms_i,"intersections")

fitzgerald_data_wt_circan <- fitzgerald_data_wt[intersections$CircaN, fitzgerald_meta_wt$sample]
fitzgerald_data_wt_mc_jtk <- fitzgerald_data_wt[intersections$`MetaCycle:JTK`, fitzgerald_meta_wt$sample]
```


# Histogram

```{r}
temp_1 <- ggplot(dat, aes(x=qvalues)) +
                geom_histogram(binwidth=0.02, colour="black", fill="white") +
                xlim(0, 1.02) +
                ggtitle(paste(a, sep="_")) +
                theme(plot.title = element_text(size = 8, face = "bold")) +
                blank_background


temp <- ggplot(dat, aes(x=qvalues)) + 
        geom_histogram(aes(y=..density..),      # Histogram with density instead of count on y-axis
                       binwidth=.02,colour="black", fill="white") +
        geom_density(alpha=.2, fill="#FF6666") +
        xlim(0, 1.02) +
        ggtitle(paste(a, sep="_")) +
        theme(plot.title = element_text(size = 8, face = "bold")) +
        blank_background
```


# t-sne

## Group

```{r}
plot_order <- c("BM", "PBZT5", "Colon", "Spleen", "Lung")
p <- tempdummy[order(match(tempdummy$tissue, plot_order)),]
p1 <- ggplot(data=p) +
      geom_point(aes(x=tSNE_1, y=tSNE_2
                 , colour=tissue
                 )
             , size = 1) +
    scale_colour_manual(values=celltype_tissue_cols) +
    labs(x="t-SNE 1", y="t-SNE 2") + 
    ggtitle("Tissue") + 
    guides(colour = guide_legend(override.aes = list(size=3))) + 
    theme(axis.text=element_text(size=8)
        , axis.title=element_text(size=8)
        , legend.text=element_text(size=7)
        , legend.position="bottom"
        , legend.title = element_blank()
        , axis.line=element_line(color="grey90")
        , panel.border = element_blank())

# Separate legend
temp <- ggplot(data=tsnedummy) +
        geom_point(aes(x=tSNE_1, y=tSNE_2, colour=Phase), size = 1)
legend <- get_legend(temp+guides(colour=guide_legend(nrow=2,byrow=TRUE,override.aes = list(size=4))))
```

## Expression

```{r}
gradient.colors <- colorRampPalette(c("grey"
                                     ,"orange"
                                     ,"red"))(3)

score.breaks <- c(min(tsnedummy$Mki67), max(tsnedummy$Mki67))
score.labels <- c(round(min(tsnedummy$Mki67),7), round(max(tsnedummy$Mki67),7))

mki67 <- ggplot(data=tsnedummy) +
      geom_point(aes(x=tSNE_1, y=tSNE_2
                     , colour=Mki67
      ), size = 1) +
      scale_color_gradientn(colours = gradient.colors
                            , guide = guide_colourbar(barheight=0.5
                                                      , label.vjust=-1)
                            , breaks=score.breaks, labels=score.labels
                            , limits = score_labels # (to set global scales)
                            ) +
      labs(x="t-SNE 1", y="t-SNE 2") + 
      ggtitle("Mki67") +
      theme(legend.position="none"
          , axis.text=element_text(size=8)
          , axis.title=element_text(size=8)
          , axis.line=element_line(color="grey90")
          , panel.border = element_blank()
          , legend.title=element_blank()
          , legend.text=element_text(size=7))
```


# BoxPlot 
```{r}
fitzgerald_vc_p <- ggplot(global_vc, aes(x=group, y=vc, fill=group)) +
                  geom_boxplot(outlier.colour="black", outlier.shape=16, outlier.size=0.5, notch=FALSE) + 
                  scale_fill_manual(values=alg_colors) +
                  xlab("") +
                  ylab("Timepoint Variation Coefficient") + 
                  theme(axis.text.x=element_text(size=10, angle=90,hjust=0.95,vjust=0.2)
                      , legend.position="none"
                      , plot.title = element_text(size = 12, face = "bold")
                      ) +
                  stat_compare_means(method = "wilcox.test"
                                     , comparisons = list(c("CircaN", "JTK")
                                                         , c("JTK", "MC")
                                                         , c("CircaN", "MC")
                                                         )) +
                  blank_background
```


```{r}
library("ggstatsplot")
# for reproducibility
set.seed(123)

temp <- ggstatsplot::ggbetweenstats(data = global_vc
                           , x = group
                           , y = vc
                           , pairwise.comparisons = TRUE
                           , type="nonparametric"
                           , mean.path = F
                           , mean.plotting = F
                           # , pairwise.display="all"
) 

temp +
  xlab("") +
  ylab("Timepoint Variation Coefficient") + 
  theme(legend.position="none") +
  # stat_compare_means(method = "wilcox.test") + 
  blank_background
```


# Session info

```{r}
xfun::session_info()
```

